$("#fullpage").fullpage({
    autoScroling:true,
    navigation:true,
    anchors:[
        "firstPage",
        "secondPage",
        "thirdPage",
        "fourthPage",
    ],
    sectionsColor:[
        "#ff5f44",
        "#0798ec",
        "#fc6c7c",
        "#fec401",
    ],
    responsiveWidth:900,
});